# Broker 配置文件

# Broker 名称
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0

# NameServer 地址
namesrvAddr = namesrv:9876

# 监听端口
listenPort = 10911

# 是否允许 Broker 自动创建 Topic
autoCreateTopicEnable = true

# 是否允许 Broker 自动创建订阅组
autoCreateSubscriptionGroup = true

# Broker 对外服务的IP地址
# Docker 环境下需要配置为容器名或者宿主机IP
brokerIP1 = broker

# 删除文件时间点，默认凌晨4点
deleteWhen = 04

# 文件保留时间，默认48小时
fileReservedTime = 48

# Broker 角色
# - ASYNC_MASTER 异步复制Master
# - SYNC_MASTER 同步双写Master
# - SLAVE 从服务器
brokerRole = ASYNC_MASTER

# 刷盘方式
# - ASYNC_FLUSH 异步刷盘
# - SYNC_FLUSH 同步刷盘
flushDiskType = ASYNC_FLUSH

# 存储路径
storePathRootDir = /home/rocketmq/store
storePathCommitLog = /home/rocketmq/store/commitlog
