services:
  nacos:
    image: nacos/nacos-server:v3.1.1
    container_name: nacos
    hostname: nacos
    ports:
      - "8848:8080"
      - "9848:9848"
      - "9849:9849"
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
      NACOS_AUTH_TOKEN: U2VjcmV0S2V5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5
      NACOS_AUTH_IDENTITY_KEY: nacos
      NACOS_AUTH_IDENTITY_VALUE: nacos
    volumes:
      - ./data:/home/nacos/data
      - ./logs:/home/nacos/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/ > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 40s
